"""Maritime domain ontology for the Knowledge Graph.

This module defines every entity label, relationship type, and property
schema used by the Conversational Maritime Service Platform.  The data
structures are intentionally plain Python dicts/lists so they can be
consumed by schema-init scripts, documentation generators, and LLM
prompt builders without any additional dependencies.
"""

from typing import Any

# =========================================================================
# 1. ENTITY LABELS
# =========================================================================
# Each key is the Neo4j label; the value is a human-readable description.

ENTITY_LABELS: dict[str, str] = {
    # ----- PhysicalEntity group -----
    "Vessel": "Any watercraft or ship operating at sea",
    "CargoShip": "Vessel designed for transporting goods",
    "Tanker": "Vessel designed for transporting liquid cargo (oil, chemicals, LNG)",
    "FishingVessel": "Vessel used for commercial or artisanal fishing",
    "PassengerShip": "Vessel carrying passengers (ferry, cruise ship)",
    "NavalVessel": "Military or coast-guard vessel",
    "AutonomousVessel": "Unmanned or remotely operated vessel (MASS)",
    "Port": "Harbour facility where vessels dock for loading/unloading",
    "TradePort": "Port primarily handling commercial cargo",
    "CoastalPort": "Smaller port serving coastal traffic",
    "FishingPort": "Port primarily serving fishing vessels",
    "PortFacility": "Infrastructure within a port (crane, storage, etc.)",
    "Berth": "Designated mooring position within a port",
    "Anchorage": "Designated area where vessels anchor outside a port",
    "Terminal": "Specialised cargo-handling area within a port",
    "Waterway": "Navigable body of water (strait, canal, river)",
    "TSS": "Traffic Separation Scheme defined by IMO",
    "Channel": "Marked navigational channel within a waterway",
    "Cargo": "Goods transported by a vessel",
    "DangerousGoods": "Cargo classified as hazardous (IMDG Code)",
    "BulkCargo": "Unpackaged bulk commodities (grain, coal, ore)",
    "ContainerCargo": "Cargo transported in ISO containers",
    "Sensor": "Any device producing observational data",
    "AISTransceiver": "Automatic Identification System transponder",
    "Radar": "Radar sensor for vessel/object detection",
    "CCTVCamera": "Closed-circuit television camera",
    "WeatherStation": "Meteorological observation station",
    # ----- SpatialEntity group -----
    "SeaArea": "Named or regulated sea region",
    "OceanEnvironment": "Ocean environmental condition (wave, current, temperature)",
    "EEZ": "Exclusive Economic Zone (200 NM from baseline)",
    "TerritorialSea": "Territorial sea (12 NM from baseline)",
    "CoastalRegion": "Coastal administrative or geographic region",
    "GeoPoint": "A single geographic coordinate (lat/lon)",
    # ----- TemporalEntity group -----
    "Voyage": "A complete journey of a vessel from origin to destination",
    "PortCall": "A vessel's visit to a specific port",
    "TrackSegment": "Contiguous segment of a vessel's AIS track",
    "Incident": "Any maritime incident or event",
    "Collision": "Incident involving collision between vessels or objects",
    "Grounding": "Incident where a vessel runs aground",
    "Pollution": "Incident involving marine pollution (oil spill, etc.)",
    "Distress": "Emergency situation requiring SAR response",
    "IllegalFishing": "Detected illegal, unreported, or unregulated (IUU) fishing",
    "WeatherCondition": "Observed or forecasted weather state for an area",
    "Activity": "A discrete operational activity performed by a vessel",
    "Loading": "Cargo loading activity at port",
    "Unloading": "Cargo unloading activity at port",
    "Bunkering": "Fuel bunkering activity",
    "Anchoring": "Activity of anchoring at an anchorage",
    "Loitering": "Abnormal loitering behaviour detected from AIS",
    "VoyageEvent": "A discrete event during a voyage (speed change, course change, sea trial)",
    "AISRecord": "Single AIS position report (location, speed, course, heading)",
    # ----- InformationEntity group -----
    "Regulation": "Maritime regulation, convention, or rule",
    "COLREG": "Convention on the International Regulations for Preventing Collisions at Sea",
    "SOLAS": "International Convention for the Safety of Life at Sea",
    "MARPOL": "International Convention for the Prevention of Pollution from Ships",
    "IMDGCode": "International Maritime Dangerous Goods Code",
    "Document": "Any document (report, paper, notice, manifest)",
    "AccidentReport": "Official maritime accident/incident report",
    "InspectionReport": "Port state control or flag state inspection report",
    "NavigationalWarning": "Safety navigation warning (NAVTEX, EGC)",
    "CargoManifest": "Cargo manifest or bill of lading",
    "DataSource": "External data provider or feed",
    "APIEndpoint": "REST/gRPC API endpoint for data ingestion",
    "StreamSource": "Real-time streaming data source (Kafka, MQTT, etc.)",
    "FileSource": "Batch file-based data source",
    "Service": "Platform micro-service or analytical service",
    "QueryService": "Service handling natural-language to Cypher queries",
    "AnalysisService": "Service performing analytical computations",
    "AlertService": "Service generating alerts and notifications",
    "PredictionService": "Service producing predictive outputs (ETA, risk)",
    "MaritimeEvent": "Unified maritime event (accident, port entry/departure, VTS event)",
    # ----- Observation group -----
    "Observation": "Base type for all observation data",
    "SARObservation": "Synthetic Aperture Radar satellite observation",
    "OpticalObservation": "Optical satellite observation",
    "CCTVObservation": "Observation derived from CCTV footage",
    "AISObservation": "Single AIS position report",
    "RadarObservation": "Observation derived from radar returns",
    "WeatherObservation": "Single meteorological observation record",
    # ----- Agent group -----
    "Organization": "Legal entity (company, government body, institute)",
    "GovernmentAgency": "Government ministry or agency",
    "ShippingCompany": "Commercial shipping or logistics company",
    "ResearchInstitute": "Research institute or university",
    "ClassificationSociety": "Ship classification society (KR, DNV, LR, etc.)",
    "Person": "An individual person",
    "VTSOperator": "Vessel Traffic Service operator (VTS controller)",
    "CrewMember": "Person serving as crew aboard a vessel",
    "Inspector": "Person conducting inspections",
    # ----- PlatformResource group -----
    "Workflow": "Automated data processing or analysis workflow definition",
    "WorkflowNode": "Individual processing step within a workflow",
    "WorkflowExecution": "A single execution instance of a workflow",
    "AIModel": "Machine learning or AI model used for inference",
    "DataPipeline": "Scheduled data ingestion or transformation pipeline",
    "AIAgent": "Autonomous AI agent that orchestrates tasks via MCP",
    "MCPTool": "Tool exposed via Model Context Protocol for agent use",
    "MCPResource": "Resource exposed via MCP (schema, data view, etc.)",
    # ----- MultimodalData group -----
    "AISData": "AIS position report time-series data batch",
    "VHFRecord": "VHF radio communication record (sender, receiver, content)",
    "CCTVRecord": "CCTV observation record (location, equipment, timestamp)",
    "SatelliteImage": "Satellite imagery (optical or SAR) raster data",
    "RadarImage": "Shore-based or vessel radar image capture",
    "SensorReading": "Time-series sensor measurement (IoT, weather station)",
    "MaritimeChart": "Electronic Navigational Chart (ENC) or sea chart data",
    "VideoClip": "Video footage from CCTV or drone surveillance",
    # ----- MultimodalRepresentation group -----
    "VisualEmbedding": "Dense vector from an image encoder",
    "TrajectoryEmbedding": "Dense vector from a trajectory encoder",
    "TextEmbedding": "Dense vector from a text encoder",
    "FusedEmbedding": "Fused multi-modal embedding vector",
    # ----- KRISO group -----
    "Experiment": "KRISO experimental test campaign",
    "TestScenario": "A specific test scenario within an experiment at KRISO",
    "MeasurementRecord": "Typed measurement result (resistance, propulsion, cavitation)",
    "TestFacility": "Physical test facility at KRISO",
    "TowingTank": "Towing tank facility for resistance/propulsion tests",
    "OceanEngineeringBasin": "Ocean engineering basin for seakeeping tests",
    "IceTank": "Ice model basin for ice-going vessel tests",
    "DeepOceanBasin": "Deep ocean engineering basin",
    "WaveEnergyTestSite": "Open-sea wave energy converter test site",
    "HyperbaricChamber": "Hyperbaric pressure testing chamber",
    "CavitationTunnel": "Cavitation tunnel for propeller/hull cavitation tests",
    "LargeCavitationTunnel": "Large cavitation tunnel (대형 캐비테이션터널)",
    "MediumCavitationTunnel": "Medium cavitation tunnel (중형 캐비테이션터널)",
    "HighSpeedCavitationTunnel": "High-speed cavitation tunnel (고속 캐비테이션터널)",
    "BridgeSimulator": "Full Mission Bridge Simulator for navigation training and research (선박운항시뮬레이터)",
    "ExperimentalDataset": "Dataset produced by a KRISO experiment",
    "TestCondition": "Environmental/operational conditions during a test",
    "ModelShip": "Scale model ship used in a KRISO experiment",
    "Measurement": "A single measurement record from a test",
    "Resistance": "Resistance measurement (drag force)",
    "Propulsion": "Propulsion performance measurement",
    "Maneuvering": "Maneuvering test measurement",
    "Seakeeping": "Seakeeping performance measurement",
    "IcePerformance": "Ice resistance/performance measurement",
    "StructuralResponse": "Structural load/response measurement",
    # ----- RBAC (Access Control) group -----
    "User": "Platform user account",
    "Role": "Access control role (admin, researcher, developer, public)",
    "DataClass": "Data classification level for access control",
    "Permission": "Specific access permission on a resource",
}


# =========================================================================
# 2. RELATIONSHIP TYPES
# =========================================================================
# Each entry describes one relationship type with its direction, end-labels,
# a description, and notable properties carried on the relationship.

RELATIONSHIP_TYPES: list[dict[str, Any]] = [
    # --- Physical ---
    {
        "type": "LOCATED_AT",
        "from_label": "Vessel",
        "to_label": "SeaArea",
        "description": "Current or last-known location of a vessel within a sea area",
        "properties": ["timestamp", "source"],
    },
    {
        "type": "DOCKED_AT",
        "from_label": "Vessel",
        "to_label": "Berth",
        "description": "Vessel is currently docked at a specific berth",
        "properties": ["since", "until"],
    },
    {
        "type": "ANCHORED_AT",
        "from_label": "Vessel",
        "to_label": "Anchorage",
        "description": "Vessel is anchored at a designated anchorage",
        "properties": ["since", "until"],
    },
    {
        "type": "HAS_FACILITY",
        "from_label": "Port",
        "to_label": "PortFacility",
        "description": "Port contains or operates a facility",
        "properties": [],
    },
    {
        "type": "CONNECTED_VIA",
        "from_label": "Port",
        "to_label": "Waterway",
        "description": "Port is accessible via a waterway",
        "properties": [],
    },
    {
        "type": "CONNECTS",
        "from_label": "Waterway",
        "to_label": "SeaArea",
        "description": "Waterway connects two sea areas",
        "properties": [],
    },
    # --- Operational ---
    {
        "type": "ON_VOYAGE",
        "from_label": "Vessel",
        "to_label": "Voyage",
        "description": "Vessel is performing a voyage",
        "properties": [],
    },
    {
        "type": "FROM_PORT",
        "from_label": "Voyage",
        "to_label": "Port",
        "description": "Voyage originates from a port",
        "properties": ["departureTime"],
    },
    {
        "type": "TO_PORT",
        "from_label": "Voyage",
        "to_label": "Port",
        "description": "Voyage is destined for a port",
        "properties": ["eta", "ata"],
    },
    {
        "type": "CONSISTS_OF",
        "from_label": "Voyage",
        "to_label": "TrackSegment",
        "description": "Voyage is composed of track segments",
        "properties": ["order"],
    },
    {
        "type": "CARRIES",
        "from_label": "Vessel",
        "to_label": "Cargo",
        "description": "Vessel is carrying cargo",
        "properties": ["quantity", "unit"],
    },
    {
        "type": "PERFORMS",
        "from_label": "Vessel",
        "to_label": "Activity",
        "description": "Vessel performs an operational activity",
        "properties": ["startTime", "endTime"],
    },
    {
        "type": "PARTICIPATED_IN",
        "from_label": "Vessel",
        "to_label": "VoyageEvent",
        "description": "Vessel participated in a voyage event",
        "properties": ["timestamp"],
    },
    {
        "type": "ARRIVED_AT",
        "from_label": "Vessel",
        "to_label": "Port",
        "description": "Vessel arrived at a port",
        "properties": ["timestamp"],
    },
    {
        "type": "DEPARTED_FROM",
        "from_label": "Vessel",
        "to_label": "Port",
        "description": "Vessel departed from a port",
        "properties": ["timestamp"],
    },
    {
        "type": "OWNED_BY",
        "from_label": "Vessel",
        "to_label": "Organization",
        "description": "Vessel is owned by an organization",
        "properties": [],
    },
    # --- Observational ---
    {
        "type": "PRODUCES",
        "from_label": "Sensor",
        "to_label": "Observation",
        "description": "Sensor produces an observation record",
        "properties": ["timestamp"],
    },
    {
        "type": "DEPICTS",
        "from_label": "Observation",
        "to_label": "Vessel",
        "description": "Observation depicts or captures a vessel",
        "properties": ["confidence"],
    },
    {
        "type": "OBSERVED_AT",
        "from_label": "Observation",
        "to_label": "GeoPoint",
        "description": "Observation was recorded at a geographic point",
        "properties": ["timestamp"],
    },
    {
        "type": "HAS_EMBEDDING",
        "from_label": "Observation",
        "to_label": "VisualEmbedding",
        "description": "Observation has an associated embedding vector",
        "properties": ["model", "version"],
    },
    {
        "type": "STORED_AT",
        "from_label": "Observation",
        "to_label": "DataSource",
        "description": "Raw observation data is stored at a data source",
        "properties": ["path", "format"],
    },
    {
        "type": "DETECTED",
        "from_label": "Observation",
        "to_label": "Vessel",
        "description": "Observation detected a vessel (automated detection)",
        "properties": ["confidence", "algorithm"],
    },
    {
        "type": "IDENTIFIED",
        "from_label": "Observation",
        "to_label": "Vessel",
        "description": "Observation identified a specific vessel",
        "properties": ["confidence", "method"],
    },
    {
        "type": "TRACKED",
        "from_label": "Observation",
        "to_label": "TrackSegment",
        "description": "Observation contributed to a track segment",
        "properties": [],
    },
    # --- Cross-modal ---
    {
        "type": "MATCHED_WITH",
        "from_label": "Observation",
        "to_label": "Observation",
        "description": "Two observations matched across modalities",
        "properties": ["similarity", "method"],
    },
    {
        "type": "SAME_ENTITY",
        "from_label": "Observation",
        "to_label": "Observation",
        "description": "Two observations confirmed to depict the same entity",
        "properties": ["confidence"],
    },
    # --- Environmental ---
    {
        "type": "AFFECTS",
        "from_label": "WeatherCondition",
        "to_label": "SeaArea",
        "description": "Weather condition affects a sea area",
        "properties": ["severity"],
    },
    {
        "type": "CAUSED_BY",
        "from_label": "Incident",
        "to_label": "WeatherCondition",
        "description": "Incident was caused or influenced by weather",
        "properties": [],
    },
    {
        "type": "BELONG_TO",
        "from_label": "SeaArea",
        "to_label": "SeaArea",
        "description": "Sea area belongs to a parent sea area (hierarchy)",
        "properties": [],
    },
    {
        "type": "OCCURRED_AT",
        "from_label": "Incident",
        "to_label": "GeoPoint",
        "description": "Incident occurred at a geographic point",
        "properties": ["timestamp"],
    },
    {
        "type": "INVOLVES",
        "from_label": "Incident",
        "to_label": "Vessel",
        "description": "Incident involves one or more vessels",
        "properties": ["role"],
    },
    # --- Regulatory ---
    {
        "type": "APPLIES_TO",
        "from_label": "Regulation",
        "to_label": "Vessel",
        "description": "Regulation applies to a class of vessels",
        "properties": ["scope"],
    },
    {
        "type": "ENFORCED_BY",
        "from_label": "Regulation",
        "to_label": "Organization",
        "description": "Regulation is enforced by an organisation",
        "properties": [],
    },
    {
        "type": "HAS_VTS_ZONE",
        "from_label": "Port",
        "to_label": "SeaArea",
        "description": "Port has a VTS-controlled sea area zone",
        "properties": [],
    },
    {
        "type": "VIOLATED",
        "from_label": "Incident",
        "to_label": "Regulation",
        "description": "Incident involved violation of a regulation",
        "properties": ["severity"],
    },
    {
        "type": "DESCRIBES",
        "from_label": "Document",
        "to_label": "Incident",
        "description": "Document describes or reports on an incident",
        "properties": [],
    },
    {
        "type": "ISSUED_BY",
        "from_label": "Document",
        "to_label": "Organization",
        "description": "Document was issued by an organisation",
        "properties": ["issueDate"],
    },
    # --- Service / Lineage ---
    {
        "type": "USES_DATA",
        "from_label": "Service",
        "to_label": "DataSource",
        "description": "Service consumes data from a data source",
        "properties": [],
    },
    {
        "type": "REQUIRES_INPUT",
        "from_label": "Service",
        "to_label": "DataSource",
        "description": "Service requires a specific input data source",
        "properties": ["format"],
    },
    {
        "type": "PRODUCES_OUTPUT",
        "from_label": "Service",
        "to_label": "DataSource",
        "description": "Service produces output stored in a data source",
        "properties": ["format"],
    },
    {
        "type": "PROVIDED_BY",
        "from_label": "DataSource",
        "to_label": "Organization",
        "description": "Data source is provided by an organisation",
        "properties": [],
    },
    {
        "type": "COMPOSED_IN",
        "from_label": "Service",
        "to_label": "Service",
        "description": "Service is composed within another service",
        "properties": [],
    },
    {
        "type": "FEEDS",
        "from_label": "Service",
        "to_label": "Service",
        "description": "Output of one service feeds into another",
        "properties": [],
    },
    {
        "type": "GENERATES",
        "from_label": "Service",
        "to_label": "Document",
        "description": "Service generates a document or report",
        "properties": [],
    },
    {
        "type": "DERIVED_FROM",
        "from_label": "DataSource",
        "to_label": "DataSource",
        "description": "Data source is derived from another source",
        "properties": ["transformation"],
    },
    # --- KRISO ---
    {
        "type": "CONDUCTED_AT",
        "from_label": "Experiment",
        "to_label": "TestFacility",
        "description": "Experiment was conducted at a test facility",
        "properties": [],
    },
    {
        "type": "TESTED",
        "from_label": "Experiment",
        "to_label": "ModelShip",
        "description": "Experiment tested a model ship",
        "properties": [],
    },
    {
        "type": "PRODUCED",
        "from_label": "Experiment",
        "to_label": "ExperimentalDataset",
        "description": "Experiment produced a dataset",
        "properties": [],
    },
    {
        "type": "UNDER_CONDITION",
        "from_label": "Experiment",
        "to_label": "TestCondition",
        "description": "Experiment was run under specific conditions",
        "properties": [],
    },
    {
        "type": "MODEL_OF",
        "from_label": "ModelShip",
        "to_label": "Vessel",
        "description": "Scale model represents a real vessel design",
        "properties": ["scale"],
    },
    {
        "type": "HAS_RAW_DATA",
        "from_label": "ExperimentalDataset",
        "to_label": "Measurement",
        "description": "Dataset contains raw measurement records",
        "properties": [],
    },
    # --- KRISO Experiment Data Relations (Section 7 pattern) ---
    {
        "type": "RECORDED_VIDEO",
        "from_label": "Experiment",
        "to_label": "VideoClip",
        "description": "Experiment was recorded on video (촬영됨)",
        "properties": ["cameraId", "angle"],
    },
    {
        "type": "MEASURED_DATA",
        "from_label": "Experiment",
        "to_label": "SensorReading",
        "description": "Experiment produced sensor measurement data (측정됨)",
        "properties": ["sensorType", "metric"],
    },
    {
        "type": "BASED_ON_CHART",
        "from_label": "Experiment",
        "to_label": "MaritimeChart",
        "description": "Experiment references a maritime chart for spatial context (기반)",
        "properties": [],
    },
    {
        "type": "COMPLIES_WITH",
        "from_label": "Experiment",
        "to_label": "Regulation",
        "description": "Experiment complies with a standard or regulation (준수)",
        "properties": ["standard", "version"],
    },
    {
        "type": "USES_SATELLITE",
        "from_label": "Experiment",
        "to_label": "SatelliteImage",
        "description": "Experiment uses satellite imagery for comparison/validation",
        "properties": [],
    },
    {
        "type": "HAS_AIS_DATA",
        "from_label": "Experiment",
        "to_label": "AISData",
        "description": "Experiment uses AIS data for validation or correlation",
        "properties": [],
    },
    {
        "type": "TESTED_IN",
        "from_label": "Vessel",
        "to_label": "TestScenario",
        "description": "Vessel was tested in a test scenario",
        "properties": [],
    },
    {
        "type": "HOSTS",
        "from_label": "TestFacility",
        "to_label": "TestScenario",
        "description": "Test facility hosts a test scenario",
        "properties": [],
    },
    {
        "type": "APPLIES",
        "from_label": "TestScenario",
        "to_label": "TestCondition",
        "description": "Test scenario applies specific test conditions",
        "properties": [],
    },
    {
        "type": "PRODUCES",
        "from_label": "TestScenario",
        "to_label": "MeasurementRecord",
        "description": "Test scenario produces measurement records",
        "properties": [],
    },
    # --- Platform ---
    {
        "type": "CONTAINS_NODE",
        "from_label": "Workflow",
        "to_label": "WorkflowNode",
        "description": "Workflow contains a processing node",
        "properties": ["order"],
    },
    {
        "type": "CONNECTS_TO",
        "from_label": "WorkflowNode",
        "to_label": "WorkflowNode",
        "description": "Data flows from one workflow node to another",
        "properties": [],
    },
    {
        "type": "USES_MODEL",
        "from_label": "WorkflowNode",
        "to_label": "AIModel",
        "description": "Workflow node uses an AI model for processing",
        "properties": ["purpose"],
    },
    {
        "type": "READS_FROM",
        "from_label": "WorkflowNode",
        "to_label": "DataSource",
        "description": "Workflow node reads from a data source",
        "properties": ["format"],
    },
    {
        "type": "WRITES_TO",
        "from_label": "WorkflowNode",
        "to_label": "DataSource",
        "description": "Workflow node writes output to a data source",
        "properties": ["format"],
    },
    {
        "type": "EXECUTION_OF",
        "from_label": "WorkflowExecution",
        "to_label": "Workflow",
        "description": "An execution instance of a workflow",
        "properties": ["startTime", "endTime", "status"],
    },
    {
        "type": "EXECUTES",
        "from_label": "AIAgent",
        "to_label": "Workflow",
        "description": "AI agent triggers or manages workflow execution",
        "properties": ["trigger"],
    },
    {
        "type": "MANAGES",
        "from_label": "AIAgent",
        "to_label": "DataSource",
        "description": "AI agent manages a data source",
        "properties": [],
    },
    {
        "type": "EXPOSES_TOOL",
        "from_label": "Service",
        "to_label": "MCPTool",
        "description": "Service exposes a tool via MCP protocol",
        "properties": [],
    },
    {
        "type": "EXPOSES_RESOURCE",
        "from_label": "Service",
        "to_label": "MCPResource",
        "description": "Service exposes a resource via MCP protocol",
        "properties": [],
    },
    {
        "type": "INVOKES",
        "from_label": "AIAgent",
        "to_label": "MCPTool",
        "description": "AI agent invokes an MCP tool",
        "properties": ["timestamp", "parameters"],
    },
    {
        "type": "ACCESSES",
        "from_label": "AIAgent",
        "to_label": "MCPResource",
        "description": "AI agent accesses an MCP resource",
        "properties": [],
    },
    {
        "type": "PIPELINE_FEEDS",
        "from_label": "DataPipeline",
        "to_label": "DataSource",
        "description": "Pipeline feeds data into a data source",
        "properties": ["schedule"],
    },
    {
        "type": "PIPELINE_READS",
        "from_label": "DataPipeline",
        "to_label": "DataSource",
        "description": "Pipeline reads data from a data source",
        "properties": [],
    },
    # --- Multimodal Data ---
    {
        "type": "AIS_TRACK_OF",
        "from_label": "AISData",
        "to_label": "Vessel",
        "description": "AIS data batch belongs to a vessel",
        "properties": [],
    },
    {
        "type": "OBSERVED_IN_AREA",
        "from_label": "AISData",
        "to_label": "SeaArea",
        "description": "AIS data batch covers observations in a sea area",
        "properties": [],
    },
    {
        "type": "CAPTURED_OVER",
        "from_label": "SatelliteImage",
        "to_label": "SeaArea",
        "description": "Satellite image covers a sea area",
        "properties": [],
    },
    {
        "type": "SAT_DEPICTS",
        "from_label": "SatelliteImage",
        "to_label": "Port",
        "description": "Satellite image depicts a port",
        "properties": [],
    },
    {
        "type": "SAT_DETECTED",
        "from_label": "SatelliteImage",
        "to_label": "Vessel",
        "description": "Satellite image detected a vessel",
        "properties": ["confidence", "bbox"],
    },
    {
        "type": "RADAR_COVERS",
        "from_label": "RadarImage",
        "to_label": "SeaArea",
        "description": "Radar image covers a sea area",
        "properties": [],
    },
    {
        "type": "READING_FROM_SENSOR",
        "from_label": "SensorReading",
        "to_label": "Sensor",
        "description": "Sensor reading originates from a sensor",
        "properties": [],
    },
    {
        "type": "READING_AT",
        "from_label": "SensorReading",
        "to_label": "GeoPoint",
        "description": "Sensor reading was taken at a location",
        "properties": [],
    },
    {
        "type": "CHART_COVERS",
        "from_label": "MaritimeChart",
        "to_label": "SeaArea",
        "description": "Maritime chart covers a sea area",
        "properties": [],
    },
    {
        "type": "VIDEO_FROM",
        "from_label": "VideoClip",
        "to_label": "Sensor",
        "description": "Video clip recorded by a sensor (CCTV/drone)",
        "properties": [],
    },
    {
        "type": "VIDEO_DEPICTS",
        "from_label": "VideoClip",
        "to_label": "Vessel",
        "description": "Video clip shows a vessel",
        "properties": ["confidence", "frameRange"],
    },
    {
        "type": "FUSED_FROM",
        "from_label": "FusedEmbedding",
        "to_label": "AISData",
        "description": "Fused embedding incorporates AIS data",
        "properties": [],
    },
    {
        "type": "FUSED_FROM_IMAGE",
        "from_label": "FusedEmbedding",
        "to_label": "SatelliteImage",
        "description": "Fused embedding incorporates satellite image",
        "properties": [],
    },
    {
        "type": "TRANSMITTED_BY",
        "from_label": "VHFRecord",
        "to_label": "Vessel",
        "description": "VHF record was transmitted by a vessel",
        "properties": ["timestamp"],
    },
    {
        "type": "INTENDED_FOR",
        "from_label": "VHFRecord",
        "to_label": "Vessel",
        "description": "VHF record was intended for a vessel or VTS",
        "properties": [],
    },
    {
        "type": "COMMUNICATE_WITH",
        "from_label": "VTSOperator",
        "to_label": "Vessel",
        "description": "VTS operator communicates with a vessel",
        "properties": ["timestamp", "channel"],
    },
    # --- RBAC (Access Control) ---
    {
        "type": "HAS_ROLE",
        "from_label": "User",
        "to_label": "Role",
        "description": "User has an assigned role",
        "properties": ["assignedAt"],
    },
    {
        "type": "CAN_ACCESS",
        "from_label": "Role",
        "to_label": "DataClass",
        "description": "Role grants access to a data classification level",
        "properties": ["accessLevel"],
    },
    {
        "type": "GRANTS",
        "from_label": "Role",
        "to_label": "Permission",
        "description": "Role grants a specific permission",
        "properties": [],
    },
    {
        "type": "BELONGS_TO",
        "from_label": "User",
        "to_label": "Organization",
        "description": "User belongs to an organization",
        "properties": [],
    },
    {
        "type": "CLASSIFIED_AS",
        "from_label": "ExperimentalDataset",
        "to_label": "DataClass",
        "description": "Dataset is classified at a security/access level",
        "properties": [],
    },
]


# =========================================================================
# 3. PROPERTY DEFINITIONS
# =========================================================================
# For key entity types, the dict maps property-name -> expected type string.

PROPERTY_DEFINITIONS: dict[str, dict[str, str]] = {
    "Vessel": {
        "mmsi": "STRING",
        "imo": "INTEGER",
        "name": "STRING",
        "callSign": "STRING",
        "vesselType": "STRING",
        "flag": "STRING",
        "grossTonnage": "FLOAT",
        "deadweight": "FLOAT",
        "length": "FLOAT",
        "beam": "FLOAT",
        "draft": "FLOAT",
        "yearBuilt": "INTEGER",
        "currentStatus": "STRING",
        "currentLocation": "POINT",
        "speed": "FLOAT",
        "course": "FLOAT",
        "heading": "FLOAT",
        "destination": "STRING",
        "eta": "DATETIME",
        "lastUpdated": "DATETIME",
    },
    "Port": {
        "unlocode": "STRING",
        "name": "STRING",
        "nameEn": "STRING",
        "country": "STRING",
        "location": "POINT",
        "portType": "STRING",
        "maxDraft": "FLOAT",
        "berthCount": "INTEGER",
        "anchorageCount": "INTEGER",
        "timezone": "STRING",
        "operatingHours": "STRING",
    },
    "Waterway": {
        "name": "STRING",
        "nameEn": "STRING",
        "waterwayType": "STRING",
        "minDepth": "FLOAT",
        "maxWidth": "FLOAT",
        "trafficDensity": "STRING",
        "tssApplicable": "BOOLEAN",
    },
    "Cargo": {
        "cargoId": "STRING",
        "cargoType": "STRING",
        "description": "STRING",
        "weight": "FLOAT",
        "volume": "FLOAT",
        "unit": "STRING",
        "hazardClass": "STRING",
        "unNumber": "STRING",
        "temperature": "FLOAT",
    },
    "WeatherCondition": {
        "timestamp": "DATETIME",
        "windSpeed": "FLOAT",
        "windDirection": "FLOAT",
        "waveHeight": "FLOAT",
        "wavePeriod": "FLOAT",
        "visibility": "FLOAT",
        "seaState": "INTEGER",
        "temperature": "FLOAT",
        "humidity": "FLOAT",
        "pressure": "FLOAT",
        "precipitation": "FLOAT",
        "riskLevel": "STRING",
        "forecast": "BOOLEAN",
    },
    "Incident": {
        "incidentId": "STRING",
        "incidentType": "STRING",
        "date": "DATETIME",
        "location": "POINT",
        "severity": "STRING",
        "description": "STRING",
        "casualties": "INTEGER",
        "pollutionAmount": "FLOAT",
        "resolved": "BOOLEAN",
        "resolvedDate": "DATETIME",
    },
    "Regulation": {
        "code": "STRING",
        "title": "STRING",
        "description": "STRING",
        "regulationType": "STRING",
        "effectiveDate": "DATE",
        "version": "STRING",
        "issuingBody": "STRING",
        "scope": "STRING",
    },
    "Document": {
        "docId": "STRING",
        "title": "STRING",
        "content": "STRING",
        "summary": "STRING",
        "docType": "STRING",
        "language": "STRING",
        "issueDate": "DATE",
        "source": "STRING",
        "textEmbedding": "LIST<FLOAT>",
    },
    "Observation": {
        "observationId": "STRING",
        "timestamp": "DATETIME",
        "location": "POINT",
        "source": "STRING",
        "modalityType": "STRING",
        "confidence": "FLOAT",
        "visualEmbedding": "LIST<FLOAT>",
        "fusedEmbedding": "LIST<FLOAT>",
        "rawDataPath": "STRING",
    },
    "Experiment": {
        "experimentId": "STRING",
        "title": "STRING",
        "objective": "STRING",
        "date": "DATE",
        "duration": "FLOAT",
        "status": "STRING",
        "principalInvestigator": "STRING",
        "projectCode": "STRING",
    },
    "TestFacility": {
        "facilityId": "STRING",
        "name": "STRING",
        "facilityType": "STRING",
        "length": "FLOAT",
        "width": "FLOAT",
        "depth": "FLOAT",
        "maxSpeed": "FLOAT",
        "waveCapability": "STRING",
        "location": "STRING",
    },
    "TestCondition": {
        "conditionId": "STRING",
        "speed": "FLOAT",
        "waveHeight": "FLOAT",
        "wavePeriod": "FLOAT",
        "waveDirection": "FLOAT",
        "windSpeed": "FLOAT",
        "currentSpeed": "FLOAT",
        "waterDepth": "FLOAT",
        "temperature": "FLOAT",
        "iceThickness": "FLOAT",
    },
    "ModelShip": {
        "modelId": "STRING",
        "scale": "FLOAT",
        "length": "FLOAT",
        "beam": "FLOAT",
        "draft": "FLOAT",
        "displacement": "FLOAT",
        "hullForm": "STRING",
        "propellerType": "STRING",
    },
    "CavitationTunnel": {
        "facilityId": "STRING",
        "name": "STRING",
        "nameEn": "STRING",
        "facilityType": "STRING",
        "length": "FLOAT",
        "width": "FLOAT",
        "depth": "FLOAT",
        "maxSpeed": "FLOAT",
        "pressureRange": "STRING",
        "waterVolume": "FLOAT",
        "location": "STRING",
    },
    "BridgeSimulator": {
        "facilityId": "STRING",
        "name": "STRING",
        "nameEn": "STRING",
        "facilityType": "STRING",
        "simulatorType": "STRING",
        "shipModels": "LIST<STRING>",
        "visualChannels": "INTEGER",
        "bridgeType": "STRING",
        "location": "STRING",
    },
    "User": {
        "userId": "STRING",
        "name": "STRING",
        "email": "STRING",
        "organization": "STRING",
        "status": "STRING",
        "createdAt": "DATETIME",
    },
    "Role": {
        "roleId": "STRING",
        "name": "STRING",
        "description": "STRING",
        "level": "INTEGER",
    },
    "DataClass": {
        "classId": "STRING",
        "name": "STRING",
        "description": "STRING",
        "level": "INTEGER",
    },
    "Workflow": {
        "workflowId": "STRING",
        "name": "STRING",
        "description": "STRING",
        "status": "STRING",
        "version": "STRING",
        "createdAt": "DATETIME",
        "updatedAt": "DATETIME",
        "schedule": "STRING",
        "tags": "LIST<STRING>",
    },
    "WorkflowNode": {
        "nodeId": "STRING",
        "nodeType": "STRING",
        "name": "STRING",
        "config": "STRING",
        "positionX": "FLOAT",
        "positionY": "FLOAT",
        "inputSchema": "STRING",
        "outputSchema": "STRING",
    },
    "AIModel": {
        "modelId": "STRING",
        "name": "STRING",
        "version": "STRING",
        "modality": "STRING",
        "framework": "STRING",
        "endpoint": "STRING",
        "inputFormat": "STRING",
        "outputFormat": "STRING",
        "metrics": "STRING",
        "deployedAt": "DATETIME",
    },
    "DataPipeline": {
        "pipelineId": "STRING",
        "name": "STRING",
        "schedule": "STRING",
        "sourceType": "STRING",
        "targetType": "STRING",
        "lastRunAt": "DATETIME",
        "status": "STRING",
        "recordsProcessed": "INTEGER",
    },
    "AIAgent": {
        "agentId": "STRING",
        "name": "STRING",
        "role": "STRING",
        "description": "STRING",
        "capabilities": "LIST<STRING>",
        "mcpEndpoint": "STRING",
        "status": "STRING",
    },
    "AISData": {
        "batchId": "STRING",
        "mmsi": "INTEGER",
        "startTime": "DATETIME",
        "endTime": "DATETIME",
        "pointCount": "INTEGER",
        "bounds": "STRING",
        "source": "STRING",
        "storagePath": "STRING",
    },
    "SatelliteImage": {
        "imageId": "STRING",
        "captureTime": "DATETIME",
        "satellite": "STRING",
        "sensorType": "STRING",
        "resolution": "FLOAT",
        "cloudCover": "FLOAT",
        "bounds": "STRING",
        "format": "STRING",
        "storagePath": "STRING",
        "visualEmbedding": "LIST<FLOAT>",
    },
    "RadarImage": {
        "imageId": "STRING",
        "captureTime": "DATETIME",
        "radarType": "STRING",
        "range": "FLOAT",
        "resolution": "FLOAT",
        "storagePath": "STRING",
    },
    "SensorReading": {
        "readingId": "STRING",
        "sensorId": "STRING",
        "metric": "STRING",
        "value": "FLOAT",
        "unit": "STRING",
        "timestamp": "DATETIME",
        "quality": "STRING",
    },
    "MaritimeChart": {
        "chartId": "STRING",
        "chartType": "STRING",
        "scale": "INTEGER",
        "edition": "STRING",
        "region": "STRING",
        "datum": "STRING",
        "updatedAt": "DATETIME",
        "storagePath": "STRING",
    },
    "VideoClip": {
        "clipId": "STRING",
        "source": "STRING",
        "startTime": "DATETIME",
        "endTime": "DATETIME",
        "duration": "FLOAT",
        "resolution": "STRING",
        "fps": "FLOAT",
        "storagePath": "STRING",
        "visualEmbedding": "LIST<FLOAT>",
    },
    "TestScenario": {
        "scenarioId": "STRING",
        "scenarioType": "STRING",
        "description": "STRING",
        "date": "DATE",
        "status": "STRING",
    },
    "MeasurementRecord": {
        "recordId": "STRING",
        "measurementType": "STRING",
        "resistanceCoefficient": "FLOAT",
        "effectiveHorsePower": "FLOAT",
        "speed": "FLOAT",
        "timestamp": "DATETIME",
    },
    "VoyageEvent": {
        "eventType": "STRING",
        "timestamp": "DATETIME",
        "location": "POINT",
        "description": "STRING",
    },
    "AISRecord": {
        "location": "POINT",
        "speed": "FLOAT",
        "course": "FLOAT",
        "heading": "FLOAT",
        "navStatus": "STRING",
        "timestamp": "DATETIME",
    },
    "VHFRecord": {
        "recordId": "STRING",
        "channel": "INTEGER",
        "content": "STRING",
        "timestamp": "DATETIME",
    },
    "CCTVRecord": {
        "recordId": "STRING",
        "cameraId": "STRING",
        "location": "POINT",
        "startTime": "DATETIME",
        "endTime": "DATETIME",
    },
    "VTSOperator": {
        "operatorId": "STRING",
        "name": "STRING",
        "station": "STRING",
        "callSign": "STRING",
    },
    "MaritimeEvent": {
        "eventId": "STRING",
        "eventType": "STRING",
        "date": "DATETIME",
        "location": "POINT",
        "severity": "STRING",
        "description": "STRING",
    },
    "OceanEnvironment": {
        "envId": "STRING",
        "waveHeight": "FLOAT",
        "wavePeriod": "FLOAT",
        "currentSpeed": "FLOAT",
        "currentDirection": "FLOAT",
        "temperature": "FLOAT",
        "salinity": "FLOAT",
        "timestamp": "DATETIME",
    },
}
