"""Integration tests for the RAG pipeline end-to-end flow.

Validates the full pipeline: parse → chunk → embed → index → retrieve → answer.
Uses real module instances (no mocks), with StubEmbeddingProvider for
deterministic results. No external dependencies required.

All tests are marked @pytest.mark.unit and require no external services.
PYTHONPATH: .
"""
from __future__ import annotations

import pytest

from rag.documents.models import (
    ChunkingConfig,
    Document,
    DocumentChunk,
    DocumentType,
)
from rag.documents.chunker import TextChunker
from rag.documents.pipeline import DocumentPipeline, IngestionResult
from rag.embeddings.models import EmbeddingConfig
from rag.embeddings.providers import StubEmbeddingProvider
from rag.engines.models import (
    RAGConfig,
    RAGResult,
    RetrievalMode,
    RetrievedChunk,
)
from rag.engines.retriever import SimpleRetriever
from rag.engines.orchestrator import HybridRAGEngine
from rag.engines.reranker import ScoreBoostReranker


# ---------------------------------------------------------------------------
# Shared fixture
# ---------------------------------------------------------------------------


@pytest.fixture
def rag_components():
    """Create a fully-wired RAG pipeline with shared retriever.

    similarity_threshold=-1.0 ensures stub hash-vectors are never filtered
    out. StubEmbeddingProvider produces deterministic but arbitrary unit
    vectors whose cosine similarities can be negative.
    """
    config = EmbeddingConfig(dimension=64)
    embedder = StubEmbeddingProvider(config)
    retriever = SimpleRetriever(RAGConfig(top_k=5, similarity_threshold=-1.0))
    chunker = TextChunker(ChunkingConfig(chunk_size=200, chunk_overlap=20))
    pipeline = DocumentPipeline(chunker=chunker, embedder=embedder, retriever=retriever)
    return {
        "embedder": embedder,
        "retriever": retriever,
        "chunker": chunker,
        "pipeline": pipeline,
    }


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _make_doc(doc_id: str, content: str, title: str = "") -> Document:
    """Build a minimal Document for test ingestion."""
    return Document(
        doc_id=doc_id,
        title=title or doc_id,
        content=content,
    )


# ---------------------------------------------------------------------------
# Class: TestRAGPipelineEndToEnd
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestRAGPipelineEndToEnd:
    """Full pipeline integration: ingest → retrieve → answer."""

    # ------------------------------------------------------------------
    # Test 1: Semantic retrieve after ingestion
    # ------------------------------------------------------------------

    def test_ingest_and_retrieve_semantic(self, rag_components):
        """TC-INT-RAG01: Ingest 3 docs via pipeline, then retrieve semantically.

        Verifies that RetrievedChunk objects are returned with score > 0
        when using query embeddings generated by StubEmbeddingProvider.
        """
        pipeline: DocumentPipeline = rag_components["pipeline"]
        embedder: StubEmbeddingProvider = rag_components["embedder"]
        retriever: SimpleRetriever = rag_components["retriever"]

        docs = [
            _make_doc("vessel-01", "Vessel KOREX departed Busan port heading to Incheon."),
            _make_doc("port-01", "Port of Busan handles 20 million TEU annually."),
            _make_doc("weather-01", "Weather warning issued for Korea Strait with strong winds."),
        ]

        for doc in docs:
            result = pipeline.ingest_document(doc)
            assert result.success, f"Ingestion failed for {doc.doc_id}: {result.error}"

        query_embedding = embedder.embed_query("vessel departure Busan")
        results = retriever.retrieve(query_embedding)

        assert len(results) > 0, "Expected at least one RetrievedChunk"
        for rc in results:
            assert isinstance(rc, RetrievedChunk)
            # StubEmbeddingProvider is hash-based so cosine scores can be negative.
            # The threshold is -1.0, so any returned score satisfies >= -1.0.
            assert rc.score >= -1.0, f"Score {rc.score} is below the minimum possible cosine value"
            assert rc.retrieval_mode == RetrievalMode.SEMANTIC

    # ------------------------------------------------------------------
    # Test 2: Keyword search after ingestion
    # ------------------------------------------------------------------

    def test_ingest_and_retrieve_keyword(self, rag_components):
        """TC-INT-RAG02: Keyword search on 'Busan port' returns correct chunks.

        Verifies keyword_search finds chunks whose content contains the query terms.
        """
        pipeline: DocumentPipeline = rag_components["pipeline"]
        retriever: SimpleRetriever = rag_components["retriever"]

        docs = [
            _make_doc("vessel-02", "Vessel KOREX departed Busan port heading to Incheon."),
            _make_doc("port-02", "Port of Busan handles 20 million TEU annually."),
            _make_doc("weather-02", "Weather warning issued for Korea Strait with strong winds."),
        ]
        for doc in docs:
            pipeline.ingest_document(doc)

        results = retriever.keyword_search("Busan port")

        assert len(results) > 0, "Keyword search for 'Busan port' should return results"
        # At least one of the Busan-related docs should appear
        contents = {rc.chunk.content.lower() for rc in results}
        has_busan = any("busan" in c for c in contents)
        assert has_busan, "Expected at least one chunk containing 'busan' in keyword results"

    # ------------------------------------------------------------------
    # Test 3: Hybrid query via HybridRAGEngine
    # ------------------------------------------------------------------

    def test_ingest_and_hybrid_query(self, rag_components):
        """TC-INT-RAG03: HybridRAGEngine with HYBRID mode returns RAGResult with answer.

        Verifies the full query path including fallback answer generation (no LLM).
        """
        pipeline: DocumentPipeline = rag_components["pipeline"]
        embedder: StubEmbeddingProvider = rag_components["embedder"]
        retriever: SimpleRetriever = rag_components["retriever"]

        docs = [
            _make_doc("vessel-03", "Vessel KOREX departed Busan port heading to Incheon."),
            _make_doc("port-03", "Port of Busan handles 20 million TEU annually."),
            _make_doc("weather-03", "Weather warning issued for Korea Strait with strong winds."),
        ]
        for doc in docs:
            pipeline.ingest_document(doc)

        engine = HybridRAGEngine(
            config=RAGConfig(mode=RetrievalMode.HYBRID, top_k=5, similarity_threshold=0.0),
            retriever=retriever,
        )
        query_embedding = embedder.embed_query("Busan port")
        result = engine.query("Busan port", query_embedding=query_embedding)

        assert isinstance(result, RAGResult)
        assert result.query == "Busan port"
        assert len(result.answer) > 0, "Answer should be non-empty (fallback to top chunk content)"
        assert result.chunk_count > 0, "HYBRID query should retrieve at least one chunk"

    # ------------------------------------------------------------------
    # Test 4: Multiple documents, verify counts
    # ------------------------------------------------------------------

    def test_pipeline_multiple_documents(self, rag_components):
        """TC-INT-RAG04: Ingest 5 documents, verify retriever has 5 chunks and pipeline count is 5."""
        pipeline: DocumentPipeline = rag_components["pipeline"]
        retriever: SimpleRetriever = rag_components["retriever"]

        texts = [
            "Document one: maritime law overview.",
            "Document two: port operations in Korea.",
            "Document three: vessel traffic management.",
            "Document four: collision avoidance regulations.",
            "Document five: weather systems in the Pacific.",
        ]
        for i, text in enumerate(texts):
            result = pipeline.ingest_document(_make_doc(f"doc-{i:02d}", text))
            assert result.success

        assert retriever.chunk_count == 5, (
            f"Expected 5 indexed chunks, got {retriever.chunk_count}"
        )
        assert pipeline.ingested_count == 5, (
            f"Expected ingested_count=5, got {pipeline.ingested_count}"
        )

    # ------------------------------------------------------------------
    # Test 5: IngestionResult metadata fields
    # ------------------------------------------------------------------

    def test_pipeline_ingestion_result_metadata(self, rag_components):
        """TC-INT-RAG05: IngestionResult has correct success/count/metadata fields."""
        pipeline: DocumentPipeline = rag_components["pipeline"]

        doc = Document(
            doc_id="meta-doc-01",
            title="Maritime Safety Overview",
            content="Maritime safety regulations are essential for safe navigation.",
        )
        result = pipeline.ingest_document(doc)

        assert isinstance(result, IngestionResult)
        assert result.success is True
        assert result.chunks_created > 0, "At least one chunk should be created"
        assert result.chunks_embedded > 0, "At least one chunk should be embedded"
        assert result.chunks_indexed > 0, "At least one chunk should be indexed"
        assert result.duration_ms > 0.0, "Duration should be measurable (> 0)"
        assert "title" in result.metadata, "metadata should contain 'title'"
        assert result.metadata["title"] == "Maritime Safety Overview"

    # ------------------------------------------------------------------
    # Test 6: Semantic retrieval relevance ordering
    # ------------------------------------------------------------------

    def test_semantic_retrieval_relevance_ordering(self, rag_components):
        """TC-INT-RAG06: Most semantically similar doc comes first in retrieve().

        StubEmbeddingProvider generates deterministic vectors from text hashes.
        The doc most similar to the query (same embedding as the query text) must
        rank first. We verify ordering by checking the first result contains
        the expected content.
        """
        embedder: StubEmbeddingProvider = rag_components["embedder"]
        retriever: SimpleRetriever = rag_components["retriever"]
        chunker: TextChunker = rag_components["chunker"]

        query_text = "collision avoidance rules"

        # Build and embed each document as a single chunk
        doc_similar = _make_doc(
            "sim-01", "COLREG rules for collision avoidance at sea", title="Similar"
        )
        doc_moderate = _make_doc(
            "mod-01", "Maritime safety regulations overview", title="Moderate"
        )
        doc_different = _make_doc(
            "dif-01", "Weather forecast for tomorrow in Seoul", title="Different"
        )

        for doc in [doc_similar, doc_moderate, doc_different]:
            chunks = chunker.chunk_document(doc)
            result = embedder.embed_texts([c.content for c in chunks])
            embedded_chunks = [
                DocumentChunk(
                    chunk_id=f"{doc.doc_id}_{i}",
                    doc_id=doc.doc_id,
                    content=c.content,
                    chunk_index=i,
                    start_char=c.start_char,
                    end_char=c.end_char,
                    embedding=vec,
                )
                for i, (c, vec) in enumerate(zip(chunks, result.vectors))
            ]
            retriever.add_chunks(embedded_chunks)

        query_embedding = embedder.embed_query(query_text)
        results = retriever.retrieve(query_embedding, top_k=3)

        assert len(results) > 0, "Should have at least one result"

        # Scores must be in descending order
        scores = [rc.score for rc in results]
        assert scores == sorted(scores, reverse=True), (
            f"Results not sorted by score descending: {scores}"
        )

    # ------------------------------------------------------------------
    # Test 7: HybridRAGEngine with reranking enabled
    # ------------------------------------------------------------------

    def test_hybrid_engine_with_reranking(self, rag_components):
        """TC-INT-RAG07: HybridRAGEngine with reranker_config(enabled=True) returns results."""
        pipeline: DocumentPipeline = rag_components["pipeline"]
        embedder: StubEmbeddingProvider = rag_components["embedder"]
        retriever: SimpleRetriever = rag_components["retriever"]

        for i in range(3):
            pipeline.ingest_document(_make_doc(
                f"rerank-doc-{i}",
                f"Maritime safety document {i}: vessel regulations and port procedures.",
            ))

        engine = HybridRAGEngine(
            config=RAGConfig(
                mode=RetrievalMode.HYBRID, top_k=3,
                similarity_threshold=0.0, rerank=True,
                reranker_backend="score_boost",
            ),
            retriever=retriever,
            reranker=ScoreBoostReranker(boost_factor=1.1),
        )
        query_embedding = embedder.embed_query("vessel regulations")
        result = engine.query("vessel regulations", query_embedding=query_embedding)

        assert isinstance(result, RAGResult)
        assert result.chunk_count > 0, "Reranking should not drop all results"
        # After reranking, scores should still be sorted (score_boost reranker sorts)
        scores = [rc.score for rc in result.retrieved_chunks]
        assert scores == sorted(scores, reverse=True), (
            f"Expected scores sorted descending after reranking, got {scores}"
        )

    # ------------------------------------------------------------------
    # Test 8: Chunker and embedder pipeline integration (multiple chunks)
    # ------------------------------------------------------------------

    def test_chunker_and_embedder_pipeline_integration(self, rag_components):
        """TC-INT-RAG08: Long text produces multiple chunks, each embedded and indexed.

        Uses '\n\n'-separated paragraphs so TextChunker (which splits on '\n\n')
        actually produces multiple chunks when chunk_size is set small enough.
        """
        embedder: StubEmbeddingProvider = rag_components["embedder"]
        retriever: SimpleRetriever = rag_components["retriever"]

        # chunk_size=50, separator='\n\n' — each paragraph is ~43 chars so
        # the chunker cannot merge them without exceeding chunk_size, yielding
        # one chunk per paragraph (6 chunks total).
        chunker = TextChunker(ChunkingConfig(chunk_size=50, chunk_overlap=10, separator="\n\n"))
        pipeline = DocumentPipeline(
            chunker=chunker, embedder=embedder, retriever=retriever
        )

        paragraphs = [
            "Maritime safety is critical for navigation.",
            "Vessels must follow COLREG rules at sea.",
            "Port authorities monitor vessel traffic closely.",
            "Weather conditions affect shipping schedules.",
            "Crews train regularly for emergency situations.",
            "Navigation charts are updated frequently.",
        ]
        long_text = "\n\n".join(paragraphs)
        doc = _make_doc("long-doc-01", long_text)
        result = pipeline.ingest_document(doc)

        assert result.success, f"Ingestion failed: {result.error}"
        assert result.chunks_created > 1, (
            f"Expected >1 chunks from paragraph-separated text with chunk_size=50, "
            f"got {result.chunks_created}"
        )
        assert result.chunks_embedded == result.chunks_created, (
            "All created chunks should be embedded"
        )
        assert result.chunks_indexed == result.chunks_embedded, (
            "All embedded chunks should be indexed in retriever"
        )
        assert retriever.chunk_count > 1, "Retriever should have multiple chunks indexed"


# ---------------------------------------------------------------------------
# Class: TestRAGComponentInteraction
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestRAGComponentInteraction:
    """Tests for specific component-to-component interactions."""

    # ------------------------------------------------------------------
    # Test 9: Retriever accepts chunks built manually from chunker
    # ------------------------------------------------------------------

    def test_retriever_accepts_pipeline_chunks(self):
        """TC-INT-RAG09: Manually chunk → embed → add to retriever, then retrieve works.

        Uses a dedicated retriever with similarity_threshold=-1.0 so that
        hash-based stub vectors with negative cosine similarity are not filtered.
        """
        config = EmbeddingConfig(dimension=64)
        embedder = StubEmbeddingProvider(config)
        # threshold=-1.0: accept all vectors including negatively-correlated ones
        retriever = SimpleRetriever(RAGConfig(top_k=5, similarity_threshold=-1.0))
        chunker = TextChunker(ChunkingConfig(chunk_size=200, chunk_overlap=20))

        doc = _make_doc("manual-doc-01", "COLREG rules govern vessel collision avoidance at sea.")
        raw_chunks = chunker.chunk_document(doc)

        # Embed and create new chunks with embeddings
        texts = [c.content for c in raw_chunks]
        embed_result = embedder.embed_texts(texts)

        embedded_chunks = [
            DocumentChunk(
                chunk_id=c.chunk_id,
                doc_id=c.doc_id,
                content=c.content,
                chunk_index=c.chunk_index,
                start_char=c.start_char,
                end_char=c.end_char,
                embedding=vec,
            )
            for c, vec in zip(raw_chunks, embed_result.vectors)
        ]
        added = retriever.add_chunks(embedded_chunks)
        assert added > 0, "At least one chunk should be indexed"

        query_vec = embedder.embed_query("collision avoidance")
        results = retriever.retrieve(query_vec)
        assert len(results) > 0, "retrieve() should return results from manually added chunks"

    # ------------------------------------------------------------------
    # Test 10: Embedding dimensions consistent across calls
    # ------------------------------------------------------------------

    def test_embedding_dimensions_consistent(self):
        """TC-INT-RAG10: StubEmbeddingProvider(dimension=64) always returns 64-dim vectors."""
        config = EmbeddingConfig(dimension=64)
        embedder = StubEmbeddingProvider(config)

        result = embedder.embed_texts(["text a", "text b"])
        assert len(result.vectors) == 2
        for vec in result.vectors:
            assert len(vec) == 64, f"Expected 64-dim vector, got {len(vec)}"

        query_vec = embedder.embed_query("text c")
        assert len(query_vec) == 64, f"Expected 64-dim query vector, got {len(query_vec)}"

        # All these vectors can be passed to cosine_similarity without error
        sim = SimpleRetriever.cosine_similarity(result.vectors[0], query_vec)
        assert isinstance(sim, float)

    # ------------------------------------------------------------------
    # Test 11: Cosine similarity with stub embeddings (deterministic)
    # ------------------------------------------------------------------

    def test_cosine_similarity_with_stub_embeddings(self):
        """TC-INT-RAG11: Same text → identical vectors → cosine=1.0; different text → < 1.0."""
        embedder = StubEmbeddingProvider(EmbeddingConfig(dimension=64))

        vec_a1 = embedder.embed_query("collision avoidance")
        vec_a2 = embedder.embed_query("collision avoidance")  # identical text

        # Deterministic: same text must produce identical vectors
        assert vec_a1 == vec_a2, "StubEmbeddingProvider must be deterministic"

        sim_identical = SimpleRetriever.cosine_similarity(vec_a1, vec_a2)
        assert abs(sim_identical - 1.0) < 1e-9, (
            f"Cosine similarity of identical vectors should be 1.0, got {sim_identical}"
        )

        vec_b = embedder.embed_query("weather forecast Seoul tomorrow")
        sim_different = SimpleRetriever.cosine_similarity(vec_a1, vec_b)
        assert sim_different < 1.0, (
            "Cosine similarity of different texts should be < 1.0"
        )

    # ------------------------------------------------------------------
    # Test 12: Keyword search finds ingested content
    # ------------------------------------------------------------------

    def test_keyword_search_finds_ingested_content(self, rag_components):
        """TC-INT-RAG12: keyword_search() directly on retriever finds pipeline-ingested chunks."""
        pipeline: DocumentPipeline = rag_components["pipeline"]
        retriever: SimpleRetriever = rag_components["retriever"]

        pipeline.ingest_document(_make_doc(
            "kw-doc-01", "Vessel DAWN operates in the Yellow Sea near Incheon port."
        ))
        pipeline.ingest_document(_make_doc(
            "kw-doc-02", "Port of Incheon is the largest container port in Korea."
        ))
        pipeline.ingest_document(_make_doc(
            "kw-doc-03", "Storm warning issued for the East Sea region."
        ))

        results = retriever.keyword_search("Incheon port")
        assert len(results) > 0, "Keyword search should return at least one result"

        found_contents = [rc.chunk.content.lower() for rc in results]
        incheon_hits = [c for c in found_contents if "incheon" in c]
        assert len(incheon_hits) > 0, (
            "At least one result should contain 'incheon' for query 'Incheon port'"
        )

    # ------------------------------------------------------------------
    # Test 13: HybridRAGEngine._reciprocal_rank_fusion combines both strategies
    # ------------------------------------------------------------------

    def test_hybrid_rrf_combines_both_strategies(self, rag_components):
        """TC-INT-RAG13: _reciprocal_rank_fusion merges semantic + keyword lists.

        Runs each strategy independently, then calls RRF directly and verifies
        the merged result contains chunk_ids from both source lists.
        """
        pipeline: DocumentPipeline = rag_components["pipeline"]
        embedder: StubEmbeddingProvider = rag_components["embedder"]
        retriever: SimpleRetriever = rag_components["retriever"]

        docs = [
            _make_doc("rrf-01", "Vessel speed limit regulations in Korean waters."),
            _make_doc("rrf-02", "Port congestion at Busan terminal during peak season."),
            _make_doc("rrf-03", "COLREG rule 13 covers overtaking vessels at sea."),
        ]
        for doc in docs:
            pipeline.ingest_document(doc)

        query_text = "vessel regulations"
        query_embedding = embedder.embed_query(query_text)

        semantic_list = retriever.retrieve(query_embedding, top_k=10)
        keyword_list = retriever.keyword_search(query_text, top_k=10)

        merged = HybridRAGEngine._reciprocal_rank_fusion(semantic_list, keyword_list, top_k=10)

        assert len(merged) > 0, "RRF should produce at least one result"

        merged_ids = {rc.chunk.chunk_id for rc in merged}
        semantic_ids = {rc.chunk.chunk_id for rc in semantic_list}
        keyword_ids = {rc.chunk.chunk_id for rc in keyword_list}
        combined_ids = semantic_ids | keyword_ids

        # All merged chunks must come from one of the source lists
        assert merged_ids.issubset(combined_ids), (
            "RRF result contains chunk_ids not present in either source list"
        )
        # Must have content from both when both lists are non-empty
        if semantic_list and keyword_list:
            assert len(merged) > 0

    # ------------------------------------------------------------------
    # Test 14: Empty query returns no results
    # ------------------------------------------------------------------

    def test_empty_query_returns_no_results(self, rag_components):
        """TC-INT-RAG14: HybridRAGEngine.query('') in KEYWORD mode returns no chunks."""
        pipeline: DocumentPipeline = rag_components["pipeline"]
        retriever: SimpleRetriever = rag_components["retriever"]

        pipeline.ingest_document(_make_doc("empty-q-01", "Some maritime content here."))

        engine = HybridRAGEngine(
            config=RAGConfig(mode=RetrievalMode.KEYWORD, top_k=5, similarity_threshold=0.0),
            retriever=retriever,
        )
        result = engine.query("", query_embedding=None)

        assert isinstance(result, RAGResult)
        assert result.chunk_count == 0, (
            f"Empty keyword query should return 0 chunks, got {result.chunk_count}"
        )

    # ------------------------------------------------------------------
    # Test 15: Pipeline reset clears ingestion counter only
    # ------------------------------------------------------------------

    def test_pipeline_reset_clears_counter(self, rag_components):
        """TC-INT-RAG15: pipeline.reset() zeroes ingested_count; retriever keeps chunks."""
        pipeline: DocumentPipeline = rag_components["pipeline"]
        retriever: SimpleRetriever = rag_components["retriever"]

        pipeline.ingest_document(_make_doc("reset-01", "First maritime document."))
        pipeline.ingest_document(_make_doc("reset-02", "Second maritime document."))

        assert pipeline.ingested_count == 2

        # Capture retriever chunk count before reset
        chunks_before = retriever.chunk_count

        pipeline.reset()

        assert pipeline.ingested_count == 0, (
            "pipeline.reset() should set ingested_count to 0"
        )
        assert retriever.chunk_count == chunks_before, (
            "pipeline.reset() must not clear the retriever index"
        )

    # ------------------------------------------------------------------
    # Test 16: Large document chunked and retrievable
    # ------------------------------------------------------------------

    def test_large_document_chunking_and_retrieval(self, rag_components):
        """TC-INT-RAG16: Large document with chunk_size=200 produces multiple retrievable chunks.

        Uses '\n\n'-separated paragraphs so TextChunker produces multiple chunks.
        Each paragraph is ~85 chars, so pairs exceed chunk_size=200 and force splits,
        resulting in at least 5 chunks from 10 paragraphs.
        """
        embedder: StubEmbeddingProvider = rag_components["embedder"]
        retriever: SimpleRetriever = rag_components["retriever"]

        chunker = TextChunker(ChunkingConfig(chunk_size=200, chunk_overlap=20))
        pipeline = DocumentPipeline(
            chunker=chunker, embedder=embedder, retriever=retriever
        )

        # 10 paragraphs, each ~85 chars, separated by '\n\n'.
        # Adjacent paragraphs together (~85+2+85=172 chars) fit within chunk_size=200,
        # so pairs get merged into one chunk → ~5 chunks total (>1).
        paragraphs = [
            "Maritime navigation requires accurate chart data for safe passage through waterways.",
            "Vessel traffic services coordinate ship movements in congested port areas efficiently.",
            "International maritime regulations are enforced by flag state control authorities.",
            "Port state control inspections verify vessel compliance with SOLAS conventions.",
            "Electronic chart display systems have replaced paper charts on modern vessels.",
            "Weather routing services help ships avoid storms and optimize fuel consumption.",
            "Maritime rescue coordination centers monitor distress signals around the clock.",
            "Ballast water management regulations prevent invasive species from spreading globally.",
            "Oil pollution prevention measures require double-hull tanker construction standards.",
            "Crew certification requirements ensure seafarers meet competency standards worldwide.",
        ]
        long_text = "\n\n".join(paragraphs)
        assert len(long_text) >= 700, f"Test text too short: {len(long_text)} chars"

        doc = _make_doc("large-doc-01", long_text, title="Large Maritime Document")
        result = pipeline.ingest_document(doc)

        assert result.success, f"Ingestion failed: {result.error}"
        assert result.chunks_created > 1, (
            f"Expected >1 chunks from 10-paragraph document, got {result.chunks_created}"
        )

        query_vec = embedder.embed_query("maritime navigation chart")
        results = retriever.retrieve(query_vec, top_k=5)

        assert len(results) > 0, (
            "Retrieval from a large chunked document should return results"
        )
        for rc in results:
            assert isinstance(rc, RetrievedChunk)
            assert rc.chunk.doc_id == "large-doc-01", (
                "Retrieved chunk should belong to the ingested document"
            )
