apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: imsp
  labels:
    app.kubernetes.io/name: imsp-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: imsp-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  clusterIP: None
  selector:
    app: imsp-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
