apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: imsp
  labels:
    app.kubernetes.io/name: imsp-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: imsp-platform
    app.kubernetes.io/managed-by: kustomize
data:
  init-imsp-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        SELECT 'CREATE DATABASE imsp'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'imsp')\gexec
    EOSQL
