apiVersion: apps/v1
kind: Deployment
metadata:
  name: imsp-gateway
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: gateway
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
