apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: prod-

patches:
  - path: api-patch.yaml
  - path: neo4j-patch.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: gateway-patch.yaml
